language: php

php:
    - 5.4
    - 5.5
    - 5.6

env:
    - NO_INTERACTION=1 TEST_TIMEOUT=300

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y libev-dev
    - sh -c "phpize && ./configure --with-rdns && make"

script:
    - sh -c "make test | tee result.txt"
    - sh test-report.sh

notifications:
    email:
        - php-rdns@weheartwebsites.de
